FROM python:3.7

# Copy application code
COPY . /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install -r requirements.txt

# Set a default port in case one isn't specified
ARG PORT=8080
ENV PORT $PORT
EXPOSE $PORT

# Start Gunicorn server
CMD gunicorn --workers=4 --bind 0.0.0.0:$PORT app:app
